# coding: utf-8

# flake8: noqa

"""
    Zenkipay API

    Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant's to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@zenki.fi
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from zenkipay-api-client.api_client import ApiClient

# import Configuration
from zenkipay-api-client.configuration import Configuration

# import exceptions
from zenkipay-api-client.exceptions import OpenApiException
from zenkipay-api-client.exceptions import ApiAttributeError
from zenkipay-api-client.exceptions import ApiTypeError
from zenkipay-api-client.exceptions import ApiValueError
from zenkipay-api-client.exceptions import ApiKeyError
from zenkipay-api-client.exceptions import ApiException
