# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import zenkipay-api-client
from zenkipay-api-client.paths.v1_pay_orders_zenki_order_id_refunds import post  # noqa: E501
from zenkipay-api-client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1PayOrdersZenkiOrderIdRefunds(ApiTestMixin, unittest.TestCase):
    """
    V1PayOrdersZenkiOrderIdRefunds unit test stubs
        Register of refunds for an order  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 201




if __name__ == '__main__':
    unittest.main()
