# coding: utf-8

"""
    Zenkipay API

    Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant's to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@zenki.fi
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from zenkipay-api-client import schemas  # noqa: F401


class CryptoPayment(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Summary of the amount paid in crypto currency by the buyer.
    """


    class MetaOapg:
        required = {
            "amount",
            "blockchain",
            "currency",
        }
        
        class properties:
            
            
            class amount(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 64
            
            
            class currency(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 5
            
            
            class blockchain(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 30
            
            
            class transactionHash(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 300
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'transactionHash':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class networkScanUrl(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 300
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'networkScanUrl':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class transactionStatus(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "CONFIRMING": "CONFIRMING",
                        "PARTIALLY_COMPLETED": "PARTIALLY_COMPLETED",
                        "COMPLETED": "COMPLETED",
                        "CANCELLED": "CANCELLED",
                        "REJECTED": "REJECTED",
                        "BLOCKED": "BLOCKED",
                        "FAILED": "FAILED",
                    }
                
                @schemas.classproperty
                def CONFIRMING(cls):
                    return cls("CONFIRMING")
                
                @schemas.classproperty
                def PARTIALLY_COMPLETED(cls):
                    return cls("PARTIALLY_COMPLETED")
                
                @schemas.classproperty
                def COMPLETED(cls):
                    return cls("COMPLETED")
                
                @schemas.classproperty
                def CANCELLED(cls):
                    return cls("CANCELLED")
                
                @schemas.classproperty
                def REJECTED(cls):
                    return cls("REJECTED")
                
                @schemas.classproperty
                def BLOCKED(cls):
                    return cls("BLOCKED")
                
                @schemas.classproperty
                def FAILED(cls):
                    return cls("FAILED")
            __annotations__ = {
                "amount": amount,
                "currency": currency,
                "blockchain": blockchain,
                "transactionHash": transactionHash,
                "networkScanUrl": networkScanUrl,
                "transactionStatus": transactionStatus,
            }
    
    amount: MetaOapg.properties.amount
    blockchain: MetaOapg.properties.blockchain
    currency: MetaOapg.properties.currency
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["blockchain"]) -> MetaOapg.properties.blockchain: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transactionHash"]) -> MetaOapg.properties.transactionHash: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["networkScanUrl"]) -> MetaOapg.properties.networkScanUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transactionStatus"]) -> MetaOapg.properties.transactionStatus: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["amount", "currency", "blockchain", "transactionHash", "networkScanUrl", "transactionStatus", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["blockchain"]) -> MetaOapg.properties.blockchain: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transactionHash"]) -> typing.Union[MetaOapg.properties.transactionHash, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["networkScanUrl"]) -> typing.Union[MetaOapg.properties.networkScanUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transactionStatus"]) -> typing.Union[MetaOapg.properties.transactionStatus, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["amount", "currency", "blockchain", "transactionHash", "networkScanUrl", "transactionStatus", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        amount: typing.Union[MetaOapg.properties.amount, str, ],
        blockchain: typing.Union[MetaOapg.properties.blockchain, str, ],
        currency: typing.Union[MetaOapg.properties.currency, str, ],
        transactionHash: typing.Union[MetaOapg.properties.transactionHash, None, str, schemas.Unset] = schemas.unset,
        networkScanUrl: typing.Union[MetaOapg.properties.networkScanUrl, None, str, schemas.Unset] = schemas.unset,
        transactionStatus: typing.Union[MetaOapg.properties.transactionStatus, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CryptoPayment':
        return super().__new__(
            cls,
            *args,
            amount=amount,
            blockchain=blockchain,
            currency=currency,
            transactionHash=transactionHash,
            networkScanUrl=networkScanUrl,
            transactionStatus=transactionStatus,
            _configuration=_configuration,
            **kwargs,
        )
