# coding: utf-8

"""
    Zenkipay API

    Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant's to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@zenki.fi
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from zenkipay-api-client import schemas  # noqa: F401


class TokenOAuth2(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "expiresIn",
            "scope",
            "accessToken",
            "tokenType",
            "refreshExpiresIn",
            "refreshToken",
        }
        
        class properties:
            
            
            class accessToken(
                schemas.StrSchema
            ):
                pass
            tokenType = schemas.StrSchema
            expiresIn = schemas.IntSchema
            __annotations__ = {
                "accessToken": accessToken,
                "tokenType": tokenType,
                "expiresIn": expiresIn,
            }
    
    expiresIn: MetaOapg.properties.expiresIn
    scope: schemas.AnyTypeSchema
    accessToken: MetaOapg.properties.accessToken
    tokenType: MetaOapg.properties.tokenType
    refreshExpiresIn: schemas.AnyTypeSchema
    refreshToken: schemas.AnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["accessToken"]) -> MetaOapg.properties.accessToken: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tokenType"]) -> MetaOapg.properties.tokenType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expiresIn"]) -> MetaOapg.properties.expiresIn: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["accessToken", "tokenType", "expiresIn", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["accessToken"]) -> MetaOapg.properties.accessToken: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tokenType"]) -> MetaOapg.properties.tokenType: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expiresIn"]) -> MetaOapg.properties.expiresIn: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["accessToken", "tokenType", "expiresIn", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        expiresIn: typing.Union[MetaOapg.properties.expiresIn, decimal.Decimal, int, ],
        scope: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        accessToken: typing.Union[MetaOapg.properties.accessToken, str, ],
        tokenType: typing.Union[MetaOapg.properties.tokenType, str, ],
        refreshExpiresIn: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        refreshToken: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TokenOAuth2':
        return super().__new__(
            cls,
            *_args,
            expiresIn=expiresIn,
            scope=scope,
            accessToken=accessToken,
            tokenType=tokenType,
            refreshExpiresIn=refreshExpiresIn,
            refreshToken=refreshToken,
            _configuration=_configuration,
            **kwargs,
        )
